const attributes = [
    "Account_Name",
    "Parent_Account",
    "Manager_Non_US",
    "Senior_Accountant",
    "Payroll_Staff",
    "Ops_Coordinator",
    "Primary_Contact_at_BooksTime_for_Client_2",
    "Start_Date_Effective_Date_in_Agreement",
    "Milestones_Reached",
    "Date_onboarding_was_completed",
    "Weekly_Review_Comments",
    "US_SA_Monthly_Review_Comments",
    "Senior_Accountant_Involvement_Frequency",
    "Services_Included_in_Most_Recent_Approved_SOW",
    "Closing_Frequency",
    "Billing_Frequency",
    "Complexity",
    "Fiscal_Year_End",
    "Price_Increase_Month",
    "id",
    "Rating",
    "Zoho_Projects_ID",
    "Relationship_Type_Client_Partner_etc",
    "For_Partners_Are_we_in_touch_with_sub_clients",
    "Industry_Shortened",
    "Lead_Source",
    "NAICS_Shortened",
    "NAICS_Code",
];

module.exports = {attributes};
